# coding: utf-8

"""
    会员系统 API

    会员系统前后端分离接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from .routers import user, admin, membership, notification, redeem

from openapi_server.api.user import router as UserApiRouter
from openapi_server.api.membership import router as MembershipApiRouter
from openapi_server.api.redeem import router as RedeemApiRouter
from openapi_server.api.notification import router as NotificationApiRouter
from openapi_server.api.admin import router as AdminApiRouter
from openapi_server.database import engine
from openapi_server.models import Base

app = FastAPI(
    title="会员系统 API",
    description="会员系统前后端分离接口文档",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # 或指定 ["http://localhost:3000"]
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(UserApiRouter, prefix="/api")
app.include_router(MembershipApiRouter, prefix="/api")
app.include_router(RedeemApiRouter, prefix="/api")
app.include_router(NotificationApiRouter, prefix="/api")
app.include_router(AdminApiRouter, prefix="/api")
app.include_router(user.router)
app.include_router(admin.router)
app.include_router(membership.router)
app.include_router(notification.router)
app.include_router(redeem.router)

# 自动建表，确保所有表结构存在
Base.metadata.create_all(bind=engine)
