# 基于官方 Python 3.11 镜像
FROM python:3.11-slim

# 直接写入阿里云源
RUN echo "deb http://mirrors.aliyun.com/debian bookworm main contrib non-free\n\
deb http://mirrors.aliyun.com/debian bookworm-updates main contrib non-free\n\
deb http://mirrors.aliyun.com/debian-security bookworm-security main contrib non-free\n" \
> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y build-essential vim curl && \
    rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /app

# 复制依赖文件
COPY requirements.txt .

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 设置环境变量
ENV PYTHONPATH=src

# 默认命令，开启热重载
CMD ["uvicorn", "openapi_server.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
