# coding: utf-8

"""
    会员系统 API

    会员系统前后端分离接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.api_membership_get200_response_local import ApiMembershipGet200ResponseLocal
from openapi_server.models.api_membership_get200_response_online import ApiMembershipGet200ResponseOnline
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ApiMembershipGet200Response(BaseModel):
    """
    ApiMembershipGet200Response
    """ # noqa: E501
    local: Optional[ApiMembershipGet200ResponseLocal] = None
    online: Optional[ApiMembershipGet200ResponseOnline] = None
    __properties: ClassVar[List[str]] = ["local", "online"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ApiMembershipGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of local
        if self.local:
            _dict['local'] = self.local.to_dict()
        # override the default output from pydantic by calling `to_dict()` of online
        if self.online:
            _dict['online'] = self.online.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ApiMembershipGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "local": ApiMembershipGet200ResponseLocal.from_dict(obj.get("local")) if obj.get("local") is not None else None,
            "online": ApiMembershipGet200ResponseOnline.from_dict(obj.get("online")) if obj.get("online") is not None else None
        })
        return _obj


